### ISSUE TITLE
Add compatibility with Infinity UI

### ISSUE THREAD

**Issue by Agagamand** [LCA-EET/AutoLoot#2]
Plz, add compatibility with Infinity UI.
This is a very popular modification. It has originated from older mod Dragonspear UI.
https://github.com/Renegade0/InfinityUI
https://forums.beamdog.com/discussion/87209/mod-infinity-ui-beta-v0-9

**Comment by LCA-EET** [comment]
I'm working on something. The menu launcher will go here: 

![image](https://github.com/user-attachments/assets/23cc2ef1-976e-47f6-9b61-af82ce1ef842)

I'd like to have kept it on the game screen but there are too many mods that tweak the UI in different ways.

**Comment by LCA-EET** [comment]
I looked into the InfinityUI mod. It's still in beta, and there were some significant rendering issues on my install. Also, large swaths of the code are commented out, making it more difficult than it needs to be to patch the UI using regex replacement. 

I'll consider adding compatibility once a stable version is released.

**Comment by Agagamand** [comment]
InfinityUI is quite stable, which can be confirmed by its numerous users. Not stable are those of its functions that relate to integration with EEex.

For example, the very useful modification [Bubbs Spell Menu Extended](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended) already has full support for InfinityUI.
Bubbs Spell Menu Extended adds a button to InfinityUI. You may be interested in the implementatio.

**Comment by LCA-EET** [comment]
Take a look at v1.2, I believe it's compatible now. If you don't like where the menu launcher button is placed, open the menu launcher and adjust the X, Y offsets, then reload your game. 

![image](https://github.com/user-attachments/assets/90471292-e4ef-45bb-b855-9c9214fd48ee)

![image](https://github.com/user-attachments/assets/c126609b-f160-4b8a-b50f-b7d31fe044c3)
